### ISSUE TITLE
Firefox context menu

### ISSUE THREAD

**Issue by mcmz** [jenskutilek/FiraSystemFontReplacement#33]
Runs nearly flawless on my system, except for the firefox context menu. Is there some kind of workaround for it?

**Comment by mcmz** [comment]
For others having an issue with that, here comes a workaround …

Edit **userChrome.css** under ~/Library/Application Support/Firefox/Profiles/[ProfileName]/chrome/ or create that files if it's not there. Paste the following code:

``` css
/* context menu (right click) */
#contentAreaContextMenu *, #contentAreaContextMenu menuitem {
    font: 300 14px 'Fira Sans', sans-serif !important;
}

/* bookmark menu item */
.bookmark-item menupopup .menuitem-iconic {
    font: 300 12px 'Fira Sans', sans-serif !important;
}

/* bookmark menu - bottommost item */
.bookmark-item menupopup menuitem {
    font: 300 14px 'Fira Sans', sans-serif !important;
}

/* all other context menues*/
menuitem {
    font: 300 14px 'Fira Sans', sans-serif !important;
}

/* url */
#urlbar {
    font: 300 12px 'Fira Sans', sans-serif !important;
}
```

NB: 'Fira Sans' has to be installed through fontbook.app or something like that, if you havent done that already. The **Fira fonts** should then be found within the ~/Library/Fonts/ folder.
